name: quran_app
description: Quran recitation app — Sheikh Bandar Baleelah
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0

  # Audio
  just_audio: ^0.9.40
  audio_service: ^0.18.13
  just_audio_background: ^0.0.1-beta.12

  # State Management
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3

  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1

  # Storage / Cache
  shared_preferences: ^2.3.1

  # Utils
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#0A2922"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#0A2922"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
